/**:
  ros__parameters:
    subscribers:
      camera_reading:
        queue_size: 1
        it_type: compressed
    publishers:
      object_detector:
        queue_size: 1
        latch: false
      bounding_boxes:
        queue_size: 1
        latch: false
      detection_image:
        queue_size: 1
        latch: true
    image_view:
      enable_opencv: false
      wait_key_delay: 3
      enable_console_output: true
